name = "hengheng"
main = "public/_worker.js"
assets = { directory = "dist" }
compatibility_date = "2024-09-01"

# Cloudflare KV Namespace Binding for hengheng
[[kv_namespaces]]
binding = "LOTTO_KV"
id = "ae6e343df2dc49f3b5def86e9926bebd"
